import Foundation

/// Lightweight performance metrics collected during chain execution.
///
/// Available via ``ChainResult/metrics`` after calling ``DocumentChain/runWithMetadata(...)``.
/// Token estimates require a ``TokenAwareBackend``; otherwise only call counts
/// and timing are populated.
public struct ChainMetrics: Sendable {
    /// Number of chunks the input was split into (0 for stuff mode).
    public let chunkCount: Int
    /// Number of LLM generate calls made during the map phase.
    public let mapCallCount: Int
    /// Number of LLM generate calls made during reduce (including hierarchical).
    public let reduceCallCount: Int
    /// Wall-clock time from chain start to completion.
    public let elapsedTime: Duration
    /// Total tokens sent to the model across all calls, if countable.
    public let estimatedInputTokens: Int?
    /// Total tokens generated by the model across all calls, if countable.
    public let estimatedOutputTokens: Int?
    /// Throughput estimate (output tokens / generation seconds), if available.
    public let tokensPerSecond: Double?

    public init(
        chunkCount: Int = 0,
        mapCallCount: Int = 0,
        reduceCallCount: Int = 0,
        elapsedTime: Duration = .zero,
        estimatedInputTokens: Int? = nil,
        estimatedOutputTokens: Int? = nil,
        tokensPerSecond: Double? = nil
    ) {
        self.chunkCount = chunkCount
        self.mapCallCount = mapCallCount
        self.reduceCallCount = reduceCallCount
        self.elapsedTime = elapsedTime
        self.estimatedInputTokens = estimatedInputTokens
        self.estimatedOutputTokens = estimatedOutputTokens
        self.tokensPerSecond = tokensPerSecond
    }
}

/// Mutable accumulator used internally during chain execution.
struct MetricsAccumulator: Sendable {
    var chunkCount: Int = 0
    var mapCallCount: Int = 0
    var reduceCallCount: Int = 0
    var inputTokens: Int = 0
    var outputTokens: Int = 0

    func finalize(elapsed: Duration) -> ChainMetrics {
        let inputEst = inputTokens > 0 ? inputTokens : nil
        let outputEst = outputTokens > 0 ? outputTokens : nil
        let tps: Double?
        if let out = outputEst, elapsed > .zero {
            let seconds = Double(elapsed.components.seconds) +
                Double(elapsed.components.attoseconds) / 1e18
            tps = seconds > 0 ? Double(out) / seconds : nil
        } else {
            tps = nil
        }
        return ChainMetrics(
            chunkCount: chunkCount,
            mapCallCount: mapCallCount,
            reduceCallCount: reduceCallCount,
            elapsedTime: elapsed,
            estimatedInputTokens: inputEst,
            estimatedOutputTokens: outputEst,
            tokensPerSecond: tps
        )
    }
}
